# Painless deployment with GitLab CI.
# Visit the docs at https://docs.gitlab.com/ce/ci/

image: painless/tox

stages:
- lint
- test

flake8:
  stage: lint
  script: tox -e flake8

pylint:
  stage: lint
  script: tox -e pylint

py35:
  stage: test
  script: tox -e py35

py36:
  stage: test
  script: tox -e py36

py37:
  stage: test
  script: tox -e py37
